Repository SWPC-Team-You-Can-Do-It/ppurisam-Backend, pull requests merged in 2024-11, with the labels that each got.

#62 refactor: webm파일을 받아 mp3로 변환 후 텍스트 출력
  Dockerfile
  build.gradle
  src/main/java/com/pprisam/backend/domain/stt/service/SttService.java
Labels: refactor

#65 refactor: Dockerfile 수정
  Dockerfile
Labels: refactor

#71 refactor: jwt 인터셉터 수정
  Dockerfile
  src/main/java/com/pprisam/backend/interceptor/AuthorizationInterceptor.java
Labels: refactor

#75 setting: docker-compose.yml파일 뿌리오 설정 추가
  docker-compose.yml
Labels: setting

#79 refactor: 연락처 조회 group_id 추가
  src/main/java/com/pprisam/backend/domain/contact/model/ContactResponse.java
  src/main/java/com/pprisam/backend/domain/contact/service/ContactService.java
Labels: refactor

#81 bug: contact 추가기능 오류 수정
  src/main/java/com/pprisam/backend/domain/contact/model/ContactRequest.java
  src/main/java/com/pprisam/backend/domain/contact/repository/entity/ContactEntity.java
  src/main/java/com/pprisam/backend/domain/contact/repository/entity/GroupEntity.java
  src/main/java/com/pprisam/backend/domain/contact/service/ContactService.java
  src/main/java/com/pprisam/backend/domain/contact/service/GroupService.java
Labels: bug

#85 refactor: 이미지 생성 프롬프팅 추가
  src/main/java/com/pprisam/backend/domain/ai/controller/ImageAIController.java
  src/main/java/com/pprisam/backend/domain/ai/model/ImageAIRequest.java
  src/main/java/com/pprisam/backend/domain/ai/repository/ThemeEntity.java
  src/main/java/com/pprisam/backend/domain/ai/repository/ThemeRepository.java
  src/main/java/com/pprisam/backend/domain/ai/service/ImageAIService.java
  src/main/java/com/pprisam/backend/domain/ai/service/TextAIService.java
Labels: refactor

#87 bug: Gradle 빌드 오류 해결
  src/main/java/com/pprisam/backend/domain/ppurio/service/RequestService.java
Labels: bug

#91 feat: 발신문자 목록 조회
  src/main/java/com/pprisam/backend/domain/ai/controller/TextAIController.java
  src/main/java/com/pprisam/backend/domain/ai/service/ImageAIService.java
  src/main/java/com/pprisam/backend/domain/ai/service/TextAIService.java
  src/main/java/com/pprisam/backend/domain/message/controller/MessageController.java
  src/main/java/com/pprisam/backend/domain/message/converter/MessageConverter.java
  src/main/java/com/pprisam/backend/domain/message/model/MessagePageResponse.java
  src/main/java/com/pprisam/backend/domain/message/repository/MessageEntity.java
  src/main/java/com/pprisam/backend/domain/message/repository/MessageRepository.java
  src/main/java/com/pprisam/backend/domain/message/service/MessageService.java
Labels: feature

#94 bug: 문자 저장 오류 수정
  src/main/java/com/pprisam/backend/domain/message/repository/MessageEntity.java
  src/main/java/com/pprisam/backend/domain/message/service/MessageService.java
Labels: bug

#96 feat: theme 테이블 조회 api 구현
  src/main/java/com/pprisam/backend/domain/ai/controller/ImageAIController.java
  src/main/java/com/pprisam/backend/domain/ai/model/ThemeResponse.java
  src/main/java/com/pprisam/backend/domain/ai/repository/ThemeEntity.java
  src/main/java/com/pprisam/backend/domain/ai/repository/ThemeLoader.java
Labels: feature

#98 feat: 문자 이미지 저장 기능
  src/main/java/com/pprisam/backend/domain/image/converter/ImageConverter.java
  src/main/java/com/pprisam/backend/domain/image/model/ImageResponse.java
  src/main/java/com/pprisam/backend/domain/image/repository/ImageEntity.java
  src/main/java/com/pprisam/backend/domain/image/repository/ImageRepository.java
  src/main/java/com/pprisam/backend/domain/message/controller/MessageController.java
  src/main/java/com/pprisam/backend/domain/message/converter/MessageConverter.java
  src/main/java/com/pprisam/backend/domain/message/model/MessageResponse.java
  src/main/java/com/pprisam/backend/domain/message/repository/MessageEntity.java
  src/main/java/com/pprisam/backend/domain/message/service/MessageService.java
  src/main/java/com/pprisam/backend/domain/ppurio/model/MessageFile.java
  src/main/java/com/pprisam/backend/domain/ppurio/model/SendRequest.java
Labels: refactor, feature

#100 refactor: 문자 이미지 저장 null 처리 추가
  src/main/java/com/pprisam/backend/domain/message/converter/MessageConverter.java
  src/main/java/com/pprisam/backend/domain/message/service/MessageService.java
Labels: refactor

#102 refactor: ai 텍스트 생성 카테고리 추가 및 프롬프트 보완
  src/main/java/com/pprisam/backend/domain/ai/controller/TextAIController.java
  src/main/java/com/pprisam/backend/domain/ai/model/TextAIRequest.java
  src/main/java/com/pprisam/backend/domain/ai/repository/TextThemeEntity.java
  src/main/java/com/pprisam/backend/domain/ai/repository/TextThemeLoader.java
  src/main/java/com/pprisam/backend/domain/ai/repository/TextThemeRepository.java
  src/main/java/com/pprisam/backend/domain/ai/service/TextAIService.java
Labels: refactor

#104 feat: cors 설정 추가
  .gitignore
  src/main/java/com/pprisam/backend/config/web/WebConfig.java
Labels: feature

#106 bug: 환경변수 읽기 수정
  src/main/java/com/pprisam/backend/BackendApplication.java
Labels: bug

#108 feat: 이미지 포함 문자 조회
  src/main/java/com/pprisam/backend/domain/message/converter/MessageConverter.java
  src/main/java/com/pprisam/backend/domain/message/repository/MessageRepository.java
  src/main/java/com/pprisam/backend/domain/message/service/MessageService.java
Labels: refactor, feature

#111 feat: 프로메테우스&그라파나 연동
  build.gradle
  docker-compose.yml
  prometheus/prometheus.yml
Labels: feature

#120 setting: prometheus.yml 스크랩 대상 추가
  prometheus/prometheus.yml
Labels: setting

#121 feat: 문자 검색
  src/main/java/com/pprisam/backend/config/elasticsearch/ElasticsearchConfig.java
  src/main/java/com/pprisam/backend/domain/message/controller/MessageController.java
  src/main/java/com/pprisam/backend/domain/message/converter/MessageConverter.java
  src/main/java/com/pprisam/backend/domain/message/repository/MessageDocumentRepository.java
  src/main/java/com/pprisam/backend/domain/message/repository/document/MessageDocument.java
  src/main/java/com/pprisam/backend/domain/message/service/MessageESService.java
  src/main/java/com/pprisam/backend/domain/message/service/MessageService.java
Labels: feature

#123 refactor: 뿌리오 전송, 문자 저장 로직 통합
  src/main/java/com/pprisam/backend/config/web/WebConfig.java
  src/main/java/com/pprisam/backend/domain/ppurio/controller/PpurioController.java
  src/main/java/com/pprisam/backend/domain/ppurio/service/PpurioService.java
  src/main/java/com/pprisam/backend/domain/ppurio/service/RequestService.java
  src/main/java/com/pprisam/backend/interceptor/AuthorizationInterceptor.java
Labels: refactor

#125 refactor: 이미지코드+webconfig 수정
  src/main/java/com/pprisam/backend/config/web/WebConfig.java
  src/main/java/com/pprisam/backend/domain/image/controller/ImageController.java
  src/main/java/com/pprisam/backend/domain/image/service/FileStorageService.java
  src/main/resources/logback-spring.xml
Labels: refactor
