Repository SWPC-Team-You-Can-Do-It/ppurisam-Backend, pull requests merged in 2024-10, with the labels that each got.

#2 [#1] 도커 세팅
  .gitignore
  Dockerfile
  src/main/resources/application.properties
Labels: setting

#14 bug: mysql연결 수정
  docker-compose.yml
Labels: bug

#16 Swagger & ObjectMapper 추가
  build.gradle
  src/main/java/com/pprisam/backend/config/objectmapper/ObjectMapperConfig.java
  src/main/java/com/pprisam/backend/config/swagger/SwaggerConfig.java
Labels: setting

#22 feat: contact 관련 엔티티 생성
  src/main/java/com/pprisam/backend/domain/contact/repository/ContactEntity.java
  src/main/java/com/pprisam/backend/domain/contact/repository/ContactRepository.java
  src/main/java/com/pprisam/backend/domain/contact/repository/GroupEntity.java
  src/main/java/com/pprisam/backend/domain/contact/repository/GroupMemberEntity.java
  src/main/java/com/pprisam/backend/domain/contact/repository/GroupMemberRepository.java
  src/main/java/com/pprisam/backend/domain/contact/repository/GroupRepository.java
  src/main/java/com/pprisam/backend/domain/user/repository/UserEntity.java
Labels: feature

#28 feat: Contact 저장 api
  src/main/java/com/pprisam/backend/domain/contact/controller/ContactController.java
  src/main/java/com/pprisam/backend/domain/contact/model/ContactDTO.java
  src/main/java/com/pprisam/backend/domain/contact/repository/ContactRepository.java
  src/main/java/com/pprisam/backend/domain/contact/repository/GroupMemberRepository.java
  src/main/java/com/pprisam/backend/domain/contact/repository/GroupRepository.java
  src/main/java/com/pprisam/backend/domain/contact/repository/entity/ContactEntity.java
  src/main/java/com/pprisam/backend/domain/contact/repository/entity/GroupEntity.java
  src/main/java/com/pprisam/backend/domain/contact/repository/entity/GroupMemberEntity.java
  src/main/java/com/pprisam/backend/domain/contact/service/ContactService.java
Labels: feature

#32 feat: contact 조회 api 구현
  src/main/java/com/pprisam/backend/domain/contact/controller/ContactController.java
  src/main/java/com/pprisam/backend/domain/contact/model/ContactDTO.java
  src/main/java/com/pprisam/backend/domain/contact/service/ContactService.java
Labels: feature

#34 refactor: contact api 수정
  src/main/java/com/pprisam/backend/domain/contact/controller/ContactController.java
  src/main/java/com/pprisam/backend/domain/contact/model/ContactDTO.java
  src/main/java/com/pprisam/backend/domain/contact/repository/entity/ContactEntity.java
  src/main/java/com/pprisam/backend/domain/contact/service/ContactService.java
  src/main/java/com/pprisam/backend/domain/user/model/UserIdResponse.java
Labels: refactor

#37 feat: contact id를 통한 상세조회 api 구현
  src/main/java/com/pprisam/backend/domain/contact/controller/ContactController.java
  src/main/java/com/pprisam/backend/domain/contact/model/ContactRequest.java
  src/main/java/com/pprisam/backend/domain/contact/model/ContactResponse.java
  src/main/java/com/pprisam/backend/domain/contact/service/ContactService.java
Labels: feature

#40 [setting] elasticsearch 초기세팅 구현
  build.gradle
  docker-compose.yml
Labels: setting

#44 feat: contact 생성 시 그룹id 입력기능 추가
  src/main/java/com/pprisam/backend/domain/contact/model/ContactRequest.java
  src/main/java/com/pprisam/backend/domain/contact/repository/entity/ContactEntity.java
  src/main/java/com/pprisam/backend/domain/contact/service/ContactService.java
Labels: feature

#46 feat: elasticsearch 수정, 삭제 기능 추가
  docker-compose.yml
  src/main/java/com/pprisam/backend/config/elasticsearch/ElasticsearchConfig.java
  src/main/java/com/pprisam/backend/domain/contact/controller/ContactController.java
  src/main/java/com/pprisam/backend/domain/contact/repository/ContactDocumentRepository.java
  src/main/java/com/pprisam/backend/domain/contact/repository/GroupMemberRepository.java
  src/main/java/com/pprisam/backend/domain/contact/repository/document/ContactDocument.java
  src/main/java/com/pprisam/backend/domain/contact/repository/document/ContactMapper.java
  src/main/java/com/pprisam/backend/domain/contact/repository/entity/ContactEntity.java
  src/main/java/com/pprisam/backend/domain/contact/service/ContactService.java
Labels: feature

#58 refactor: 이미지 생성 기능 수정
  .gitignore
  docker-compose.yml
  src/main/java/com/pprisam/backend/config/web/WebConfig.java
  src/main/java/com/pprisam/backend/domain/ai/service/ImageAIService.java
Labels: refactor
